package com.smi.test.presentation

object Const {
    const val PERMISSIONS_REQUEST_ACCESS_FINE_LOCATION=101
    const val AUTHORIZATION="Authorization"
    const val LIST_PLACES_LOCATION="LIST_PLACES_LOCATION"
    const val LIST_PLACES_LOCATION_NEW_ROUTES="LIST_PLACES_LOCATION_NEW_ROUTES"
    const val DOCUMENTS_UPLOADED =  "DOCUMENTS_UPLOADED"
    const val APP_LANGUAGE = "APP_LANGUAGE"
    const val USER_INFO = "USER_INFO"
    const val USER_INFO_PRO = "USER_INFO_PRO"
    const val USER_FROM_OTHER_APPS_FB = "USER_FROM_OTHER_APPS_FB"
    const val USER_FROM_OTHER_APPS = "USER_FROM_OTHER_APPS"
    const val RC_SIGN_IN: Int=1601
    const val USER_LOAD_SIGNUP = "USER_LOAD_SIGNUP"
    const val USER_PICTURE_TO_UPLOAD = "USER_PICTURE_TO_UPLOAD"
    const val DEVICE_ID = "DEVICE_ID"
    const val ACCOUNT_CHOOSE = "ACCOUNT_CHOOSE"
    const val TO_IN_PROGRESS = "TO_IN_PROGRESS"
    const val IMAGE = "IMAGE"
    const val IMAGE_TRUCK = "IMAGE_TRUCK"

    const val LAST_LOCATION = "LAST_LOCATION"
    const val LAST_LOCATION_DETECTED = "LAST_LOCATION_DETECTED"
    const val ALL_TARIF_DETAILS = "ALL_TARIF_DETAILS"
    const val HELP_FROM_CLIENT = "HELP_FROM_CLIENT"
    const val SETTING = "SETTING"
    const val FOREGROUND = "FOREGROUND"
    const val LIST_BRANCH = "LIST_BRANCH"
    const val LIST_USER_TYPE = "LIST_USER_TYPE"
    const val LIST_COUNTRY = "LIST_COUNTRY"
    const val USER_TYPE = "USER_TYPE"
    const val REQUEST_CODE_DOC = 103


    const val LANGUAGE_ENGLISH = "en"
    const val LANGUAGE_ENGLISH_COUNTRY = "US"
    const val LANGUAGE_ARABE = "ar"
    const val LANGUAGE_ARABE_COUNTRY = "AR"
}
